import { IProduct } from "../interfaces/IProduct";

export const db: IProduct[] = [
    {
        id: 1,
        name: 'Lukather',
        image: 'guitarra_01',
        description: 'Morbi ornare augue nisl, vel elementum dui mollis vel. Curabitur non ex id eros fermentum hendrerit.',
        price: 299,
    },
    {
        id: 2828,
        name: 'Clarinete',
        image: 'clarinete_01',
        description: 'Morbi ornare augue nisl, vel elementum dui mollis vel. Curabitur non ex id eros fermentum hendrerit.',
        price: 510,
    },
    {
        id: 2,
        name: 'SRV',
        image: 'guitarra_02',
        description: 'Morbi ornare augue nisl, vel elementum dui mollis vel. Curabitur non ex id eros fermentum hendrerit.',
        price: 349,
    },
    {
        id: 3232,
        name: 'Mezclador',
        image: 'mezclador_01',
        description: 'Morbi ornare augue nisl, vel elementum dui mollis vel. Curabitur non ex id eros fermentum hendrerit.',
        price: 661,
    },
    {
        id: 3,
        name: 'Borland',
        image: 'guitarra_03',
        description: 'Morbi ornare augue nisl, vel elementum dui mollis vel. Curabitur non ex id eros fermentum hendrerit.',
        price: 329,
    },
    {
        id: 4,
        name: 'VAI',
        image: 'guitarra_04',
        description: 'Morbi ornare augue nisl, vel elementum dui mollis vel. Curabitur non ex id eros fermentum hendrerit.',
        price: 299,
    },
    {
        id: 4848,
        name: 'Tambor',
        image: 'tambor_01',
        description: 'Morbi ornare augue nisl, vel elementum dui mollis vel. Curabitur non ex id eros fermentum hendrerit.',
        price: 481,
    },
    {
        id: 4343,
        name: 'Violin',
        image: 'violin_01',
        description: 'Morbi ornare augue nisl, vel elementum dui mollis vel. Curabitur non ex id eros fermentum hendrerit.',
        price: 445,
    },
    {
        id: 5,
        name: 'Thompson',
        image: 'guitarra_05',
        description: 'Morbi ornare augue nisl, vel elementum dui mollis vel. Curabitur non ex id eros fermentum hendrerit.',
        price: 399,
    },
    {
        id: 5353,
        name: 'Batería',
        image: 'bateria_01',
        description: 'Morbi ornare augue nisl, vel elementum dui mollis vel. Curabitur non ex id eros fermentum hendrerit.',
        price: 399,
    },
    {
        id: 6,
        name: 'White',
        image: 'guitarra_06',
        description: 'Morbi ornare augue nisl, vel elementum dui mollis vel. Curabitur non ex id eros fermentum hendrerit.',
        price: 329,
    },
    {
        id: 7,
        name: 'Cobain',
        image: 'guitarra_07',
        description: 'Morbi ornare augue nisl, vel elementum dui mollis vel. Curabitur non ex id eros fermentum hendrerit.',
        price: 349,
    },
    {
        id: 7272,
        name: 'Sasofón',
        image: 'sasofon_01',
        description: 'Morbi ornare augue nisl, vel elementum dui mollis vel. Curabitur non ex id eros fermentum hendrerit.',
        price: 561,
    },
    {
        id: 8,
        name: 'Dale',
        image: 'guitarra_08',
        description: 'Morbi ornare augue nisl, vel elementum dui mollis vel. Curabitur non ex id eros fermentum hendrerit.',
        price: 379,
    },
    {
        id: 9,
        name: 'Krieger',
        image: 'guitarra_09',
        description: 'Morbi ornare augue nisl, vel elementum dui mollis vel. Curabitur non ex id eros fermentum hendrerit.',
        price: 289,
    },
    {
        id: 9090,
        name: 'Arpa',
        image: 'arpa_01',
        description: 'Morbi ornare augue nisl, vel elementum dui mollis vel. Curabitur non ex id eros fermentum hendrerit.',
        price: 581,
    },
    {
        id: 10,
        name: 'Campbell',
        image: 'guitarra_10',
        description: 'Morbi ornare augue nisl, vel elementum dui mollis vel. Curabitur non ex id eros fermentum hendrerit.',
        price: 349,
    },
    {
        id: 11,
        name: 'Reed',
        image: 'guitarra_11',
        description: 'Morbi ornare augue nisl, vel elementum dui mollis vel. Curabitur non ex id eros fermentum hendrerit.',
        price: 399,
    },
    {
        id: 12,
        name: 'Hazel',
        image: 'guitarra_12',
        description: 'Morbi ornare augue nisl, vel elementum dui mollis vel. Curabitur non ex id eros fermentum hendrerit.',
        price: 379,
    },
  ]